### ISSUE TITLE
How to install/use with Zeal

### ISSUE THREAD

**Issue by edouard-lopez** [dan-c-underwood/fish-dash#1]
**related:** 
* fish-shell/fish-shell#3935
* Kapeli/Dash-User-Contributions#1355
---

Hi, I'm looking for a fish docset but not sure how I can use your with `zeal`. 

Zeal allow me to _add feed URL_ but what should I use?

**Comment by dan-c-underwood** [comment]
Hi there! Currently this docset is in the user contributed section of Dash - there are some ways of adding it I believe. You can find them in the following thread: https://github.com/zealdocs/zeal/issues/170

I will leave this issue open until there's a more supported method of adding the docset!

**Comment by davewongillies** [comment]
@edouard-lopez add [this feed](https://zealusercontributions.herokuapp.com/docsets/fish.xml) in Tools -> Docsets -> Add feed.

To get the feeds for other Dash user contributed docsets for use in Zeal, you can get their feeds [here](https://zealusercontributions.herokuapp.com/).
