### ISSUE TITLE
Update fish docset to fish 2.7

### ISSUE THREAD

**Issue by andreiborisov** [dan-c-underwood/fish-dash#3]
Hi, there is a new fish in town! Can you update the docset?

**Comment by dan-c-underwood** [comment]
Hi, I’ll get the new docset version built and pushed across this weekend 🙂

**Comment by andreiborisov** [comment]
That's awesome! Thanks you!

**Comment by dan-c-underwood** [comment]
New version has been built - awaiting approval of pull request https://github.com/Kapeli/Dash-User-Contributions/pull/1841 🙂

**Comment by dan-c-underwood** [comment]
Pull request accepted, closing this issue.
