### ISSUE TITLE
Update docset for new major fish release

### ISSUE THREAD

**Issue by andreiborisov** [dan-c-underwood/fish-dash#4]
We have new major fish release: 3.0.
The layout of the pages seems to be changed but not by much, so update process should be straightforward.

**Comment by andreiborisov** [comment]
I can confirm, there is no modifications needed, just simple rebuild

**Comment by andreiborisov** [comment]
I've submitted a PR: https://github.com/Kapeli/Dash-User-Contributions/pull/2175

**Comment by dan-c-underwood** [comment]
Hey - thanks for getting that submitted! 🙂 I’ll close this once the pull request has been accepted.
