### ISSUE TITLE
Archiving of the repo

### ISSUE THREAD

**Issue by andreiborisov** [dan-c-underwood/fish-dash#7]
Hi!

fish guys just recently changed how they generate docs and unfortunately, your scripts are no longer working...

I've maid another repo with a different approach to the generation and would love to carry the torch and continue to maintain this docset if that's OK: https://github.com/schrodincat/dash-fish.

**Comment by dan-c-underwood** [comment]
Hey! Yeah I spotted that the format had changed. I'm perfectly happy for you to take over the torch on generating the docset 🙂. I'll archive this repo and point people towards yours.
